version: 2.1

workflows:
  test:
    jobs:
      - unit-tests

jobs:
  unit-tests:
    docker:
      - image: circleci/node:14.18.3
    steps:
      - checkout
      - run:
          name: Versions
          command: node -v && npm -v && yarn -v
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build
          command: yarn build
